[package]
name = "module-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros", "signal"] }
axum = "0.7.5"
serde_json = "1.0.118"
serenity = "0.12.2"
poise = "0.6.1"
dotenv = "0.15.0"
log = "0.4.21"
env_logger = "0.11.3"
